{% set name = "WTForms" %}
{% set version = "2.2.1" %}
{% set sha256 = "0cdbac3e7f6878086c334aa25dc5a33869a3954e9d1e015130d65a69309b3b61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - wtforms
    - wtforms.csrf
    - wtforms.ext
    - wtforms.ext.appengine
    - wtforms.ext.csrf
    - wtforms.ext.dateutil
    - wtforms.ext.django
    - wtforms.ext.django.templatetags
    - wtforms.ext.i18n
    - wtforms.ext.sqlalchemy
    - wtforms.fields
    - wtforms.widgets

about:
  home: http://wtforms.simplecodes.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'A flexible forms validation and rendering library for Python'
  doc_url: http://wtforms.readthedocs.io
  dev_url: https://github.com/wtforms/wtforms

extra:
  recipe-maintainers:
    - mcs07
