{% set name = "wtforms" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df3e6b70f3192e92623128123ec8dca3067df9cfadd43d59681e210cfb8d4682

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - hatchling
    - setuptools  # [py>=312]
    - babel >=2.6.0
  run:
    - python
    - markupsafe

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - babel >=2.6.0
    - email_validator
  imports:
    - wtforms
    - wtforms.csrf
    - wtforms.fields
    - wtforms.widgets
  commands:
    - pip check
    - pytest tests -v  # [not win]
    # Assertion fail on Windows
    - pytest tests -v -k "not (test_basic)"  # [win]

about:
  home: https://wtforms.simplecodes.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A flexible forms validation and rendering library for Python
  description: |
    WTForms is a flexible forms validation and rendering library for Python web development. 
    It can work with whatever web framework and template engine you choose. 
    It supports data validation, CSRF protection, internationalization (I18N), and more. 
    There are various community libraries that provide closer integration with popular frameworks.
  doc_url: https://wtforms.readthedocs.io
  dev_url: https://github.com/wtforms/wtforms

extra:
  recipe-maintainers:
    - mcs07
    - synapticarbors
