{% set name = "WTForms" %}
{% set version = "3.2.1" %}
{% set sha256 = "df3e6b70f3192e92623128123ec8dca3067df9cfadd43d59681e210cfb8d4682" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/W/WTForms/wtforms-3.2.1.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - babel >=2.6.0
    - hatchling
  run:
    - python
    - markupsafe

test:
  imports:
    - wtforms
    - wtforms.csrf
    - wtforms.fields
    - wtforms.widgets

about:
  home: http://wtforms.simplecodes.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A flexible forms validation and rendering library for Python
  doc_url: http://wtforms.readthedocs.io
  dev_url: https://github.com/wtforms/wtforms

extra:
  recipe-maintainers:
    - mcs07
    - synapticarbors
