travis:
  secure:
    BINSTAR_TOKEN: Or9L0/aYGpIYpAXqB8qEomkE9PAIAKsanvlCIWO+0PGGtW5+7BOk8BUckHLE1UtAmUIgeoTDGH5KRgUgmn8Ydem5lJnJB2xZOTr7zoMpl39IS2amz2wDNaEPygXHhrGpM944M1H2NE9CSc3neSd2lZNXkIlpvEKzHc3XleyipClk54Ayo6TjrBl8RIBQ2eprVkH4SDzB8Ig5H1z4tYeI6EWWsIs1i8vcRFjlKIOt0Xs2BvRFsBkq4XQw7dT40Ih2ki5tvBNz8HUp3jkNqaXueYDb+fyV/kHv+qfVkM0F0AdKMprH2acH5Rmd9yeyYC3wxOnTGjEfUL9g/jxV7u5rCTQeRYpSmW+Llp5Z4IBCIlzbgXWuf3i/VP9HlSVpeaO5gN7p/4Cf+bcQ44Yl6VV/Ucg+NmlDL7FoIFJ6fy/f7kyXqlRxKXDSIiJDWm2S5qMatbAnVwXrgLL4NwnnObDx5hCdNHHn810vJ48mwhQIYYR//EKgMo8T5wxzo1uCIDT24cAkFxqFuFGotjlP8FIz3U5iQMRE2sef2hQU33vI0ZnRdNJ1uJ0HTa0O3IkvcVcscoiHYHGq8Dt0aNneAbeTU4F7wNcZOEAYOpcZRPE17mWGJexJBys7yW4qt73ofNRn0JnTNHNE1XN7WylYznI+MaevCeBAJqnye7p7aQwnC8I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
